# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# A.R.py
# Created on: 2022-07-02 15:41:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: A.R <Input_series> <Output_graph_name__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_series = arcpy.GetParameterAsText(0)
if Input_series == '#' or not Input_series:
    Input_series = "SERIES=line:vertical DATA=E:\\Projet Of Daryan\\GDB\\Daryan_Edited.gdb\\PC_Cross_Section\\PCQ_B_760_1_1_1 X=Date Y=A_C SORT=DESC;GRAPH=general;LEGEND=general;AXIS=left TITLE=A.R;AXIS=right;AXIS=bottom TITLE=Date;AXIS=top" # provide a default value if unspecified

Output_graph_name__2_ = arcpy.GetParameterAsText(1)
if Output_graph_name__2_ == '#' or not Output_graph_name__2_:
    Output_graph_name__2_ = "C:\\Users\\Motasam\\Desktop\\Ru\\x" # provide a default value if unspecified

# Local variables:
Graph_grf = "E:\\Projet Of Daryan\\GDB\\Graph.grf"

# Process: Make Graph (2)
arcpy.MakeGraph_management(Graph_grf, Input_series, Output_graph_name__2_)

