# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Settlement.py
# Created on: 2022-07-02 15:45:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Settlement <Input_series> <Output_graph_name__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_series = arcpy.GetParameterAsText(0)
if Input_series == '#' or not Input_series:
    Input_series = "SERIES=line:vertical DATA=E:\\Projet Of Daryan\\GDB\\Daryan_Edited.gdb\\Displacement\\IN_E_2_1 X=Total_S Y=Instal_E SORT=DESC;GRAPH=general;LEGEND=general;AXIS=left TITLE=settle;AXIS=right;AXIS=bottom;AXIS=top" # provide a default value if unspecified

Output_graph_name__2_ = arcpy.GetParameterAsText(1)
if Output_graph_name__2_ == '#' or not Output_graph_name__2_:
    Output_graph_name__2_ = "C:\\Users\\Motasam\\Desktop\\Ru\\x" # provide a default value if unspecified

# Local variables:
Graph_of_IN_E_2_1_grf = "E:\\Projet Of Daryan\\GDB\\Graph of IN_E_2_1.grf"

# Process: Make Graph (2)
arcpy.MakeGraph_management(Graph_of_IN_E_2_1_grf, Input_series, Output_graph_name__2_)

